name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Run lint
  #       continue-on-error: true
  #       if: success()
  #       run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    # needs: [lint]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        if: success()
        run: make test
